### ISSUE TITLE
Ace.dart

### ISSUE THREAD

**Issue by ppvk** [rmsmith/ace.dart#59]
Although I understand how things go, it makes me sad to see this library lose it's maintainer.

If you don't mind me asking, are you using a different library now, or perhaps is the project finished?

**Comment by rmsmith** [comment]
@ppvk I started this library for a prototype that didn't stick around, so things are finished on my end.  It was also used by the Chrome Dev Editor but that project is no longer active, so I'm not aware of any active users.  If you are using the library I'd be happy to transfer you the repository.  Recently I tried dropping in the latest `ace-builds` but several tests failed and it looked like it would take some amount of work to get them to all pass.

**Comment by ppvk** [comment]
I've been thinking all night about it, but I wouldn't be able to give ace.dart proper maintenance. I'm a bit overextended at the moment, and am planning to retire a few of my own projects as well.

While I do use the library [here](http://ppvk.github.io/wren-nest/), I'm finding that directly using `JsObject`s in dart isn't all too hard, so I know I'll be fine.

Good luck to you, and I hope you find your maintainer.

**Comment by rmsmith** [comment]
I am glad to hear that this library helped another project, so thanks for sharing.  Maybe someday you can write the Wren's Nest in Wren :)

Yes, the `JsObject` stuff is fairly straightforward once you get the hang of it.  I have heard there is an even newer/better way to do js-interop in Dart now, so that might be worth looking into also.

cheers
